/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#6a1f76",
        "on-secondary-container": "#f1f9ff",
        "surface-container": "#1a1919",
        "error-container": "#9f0519",
        "surface-tint": "#85adff",
        "secondary-fixed": "#97daff",
        "tertiary-fixed": "#f39cfb",
        "tertiary-dim": "#e48fec",
        "surface-container-high": "#201f1f",
        "on-primary-fixed": "#000000",
        "inverse-on-surface": "#565554",
        "outline-variant": "#494847",
        "inverse-surface": "#fcf8f8",
        "on-tertiary-container": "#60136d",
        "inverse-primary": "#005bc2",
        "surface-container-lowest": "#000000",
        "error-dim": "#d7383b",
        "primary-dim": "#0070eb",
        "surface-bright": "#2c2c2c",
        "on-tertiary-fixed": "#41004d",
        "on-background": "#ffffff",
        "error": "#ff716c",
        "tertiary-container": "#f39cfb",
        "primary-fixed": "#6c9fff",
        "surface-container-low": "#131313",
        "primary": "#85adff",
        "on-secondary-fixed-variant": "#005775",
        "background": "#0e0e0e",
        "on-surface-variant": "#adaaaa",
        "secondary-fixed-dim": "#6bcfff",
        "on-tertiary": "#6b1f77",
        "on-primary": "#002c65",
        "on-error-container": "#ffa8a3",
        "surface-dim": "#0e0e0e",
        "on-error": "#490006",
        "on-secondary-fixed": "#00394d",
        "surface-variant": "#262626",
        "outline": "#777575",
        "primary-fixed-dim": "#5191ff",
        "secondary": "#00c1fd",
        "secondary-dim": "#00b2eb",
        "surface-container-highest": "#262626",
        "secondary-container": "#006688",
        "on-surface": "#ffffff",
        "tertiary": "#fab0ff",
        "on-secondary": "#00374b",
        "on-primary-container": "#00214f",
        "surface": "#0e0e0e",
        "primary-container": "#6c9fff",
        "tertiary-fixed-dim": "#e48fec",
        "on-primary-fixed-variant": "#002a61"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
